{% set python_min = "3.10" %}
{% set name = "vidigi" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/vidigi-{{ version }}.tar.gz
  sha256: 25b287e60866aa3a347cdfbdf1064bcfbdce38990c35c13631acd4d999acbc25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - plotly >=5.12.0,<7.0.0
    - numpy >=1.26.2,<3.0.0
    - pandas >=2.0.1,<3.0.0
    - simpy >=4.0.0,<5.0.0
    - pydantic >=2.0.0,<3.0.0
    - webcolors >=24.11.1
    - graphviz>=0.15,<1.0.0
    - ipywidgets>=8.0.0
    - ipycytoscape>=1.2.0,<2.0.0

test:
  imports:
    - vidigi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hsma-tools.github.io/vidigi/vidigi_docs/
  summary: A package for creating animated visualisations of queues and pathways from historical data or simulations
  dev_url: https://github.com/hsma-tools/vidigi
  license: MIT
  license_family: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Bergam0t
